CentralServer.class: CentralServer.java

	javac CentralServer.java Conector.java Distrito.java Cliente.java
	javac ClienteMulti.java Distrito.java Titan.java
	javac DistritoServer.java Distrito.java Titan.java
 
	
	


clean: 
	rm -f *.class 
